In [ ]:
print ("Hello")

Hello


In [ ]:
import time

print(time.ctime())

Thu Feb  6 04:44:57 2025


In [ ]:
z = "Hello"
y = 28
c = 29.5
f = ["Apple, Rambutan"]

z, y, c, f
print(z, y, c, f)

Hello 28 29.5 ['Apple, Rambutan']


In [ ]:
o = int(1)
y = int(2.8)
z = int("4")
j = str(20)

print(o, y, z, j)

1 2 4 20


In [ ]:
a = "hello"
b = " world"
c = a+b

print(c)

hello world


In [ ]:
a = "Hello World"

print(a[1])

print(len(a))

e
11


In [ ]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(c[:5])

d = "BINUS Univ"
print(d[2:])

NUS
BINUS
NUS Univ


In [ ]:
a = "Hello"
print(a.upper())

b = "Hello"
print(b.lower())

c = "Hello"
print(a.replace("H", "J"))

HELLO
hello
Jello


In [ ]:
nama = "sam"
a = 19
string = "nama saya {} umur {}"
print(string.format(nama,a))

nama saya sam umur 19


In [ ]:
nama = "Grace"
for i in enumerate(nama):
  print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a=b")

In [ ]:
perbandingan (3,7)

a kurang dari b


In [ ]:
i=1
while i<6:
  print(1)
  i += 1

1
1
1
1
1


In [ ]:
i=3
for i in range(0,6):
  print(i)

0
1
2
3
4
5


In [ ]:
angka = int(input("Masukan angka:"))

if 2 >= angka <= 40:
  if angka %2==0:
    print("angka genap")
  else:
    print("angka ganjil")

Masukan angka:7


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2 ,3], [3, 6, 7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8, 2, 9], [3, 5, 7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array ([10, 9, 8, 7, 5, 6])

print("Rata-rata:", np.mean(data))
print("Maksimum:", np.max(data))
print("Minimum", np.min(data))
print("Standar Deviasi:", np.std(data))

Rata-rata: 7.5
Maksimum: 10
Minimum 5
Standar Deviasi: 1.707825127659933


In [ ]:
def calculate(UAS, UTS, ASG):
    return (UAS * 0.5) + (UTS * 0.3) + (ASG * 0.2)

def grading(final_score):
    if 90 <= final_score <= 100:
        return "A"
    elif 85 <= final_score <= 89:
        return "A-"
    elif 80 <= final_score <= 84:
        return "B+"
    elif 75 <= final_score <= 79:
        return "B"
    elif 70 <= final_score <= 74:
        return "B-"
    elif 65 <= final_score <= 69:
        return "C"
    elif 60 <= final_score <= 64:
        return "D"
    elif 11 <= final_score <= 59:
        return "E"
    else:
        return "F"

while True:
    username = input("Masukkan username: ")
    password = input("Masukkan password: ")
    if password == "admin123":
        print("Login berhasil!\n")
        break
    else:
        print("Password salah! Coba lagi.\n")

nama = input("Masukkan nama mahasiswa: ")

def input_nilai(prompt):
    while True:
        try:
            nilai = float(input(prompt))
            if 0 <= nilai <= 100:
                return nilai
            else:
                print("Nilai harus antara 0 - 100.")
        except ValueError:
            print("Harap masukkan angka yang valid.")

UAS = input_nilai("Masukkan nilai UAS: ")
UTS = input_nilai("Masukkan nilai UTS: ")
ASG = input_nilai("Masukkan nilai ASG: ")

final_score = calculate(UAS, UTS, ASG)
grade = grading(final_score)

print("\n============================================")
print(f"Hasil perolehan nilai {nama}")
print(f"Final Score: {final_score:.2f}")
print(f"Grade: {grade}")
